# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/ceserani/gt-book" }

# gem "rails"

# gem "jekyll", "~> 4.0"
gem "jekyll", "~> 3.9.0"
gem "github-pages", "~> 228", group: :jekyll_plugins
gem "webrick"